AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: "Report my little brother's grades via SMS."

Resources:
  BigBrotherFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lib/big_brother.entry
      Runtime: ruby2.5
      Timeout: 300
      Policies:
      - DynamoDBCrudPolicy:
          TableName: !Ref AssignmentDDBTable
      Environment:
        Variables:
          DDB_TABLE: !Ref AssignmentDDBTable
          RECIPIENTS: '{{resolve:ssm:RECIPIENTS:1}}'
          SCHOOL_ID: '{{resolve:ssm:SCHOOL_ID:1}}'
          SCHOOL_PASSWORD: '{{resolve:ssm:SCHOOL_PASSWORD:1}}'
          SCHOOL_USERNAME: '{{resolve:ssm:SCHOOL_USERNAME:1}}'
          TWILIO_ACCOUNT_SID: '{{resolve:ssm:TWILIO_ACCOUNT_SID:1}}'
          TWILIO_AUTH_TOKEN: '{{resolve:ssm:TWILIO_AUTH_TOKEN:1}}'
  AssignmentDDBTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      PrimaryKey:
        Name: hash
        Type: String
  ScheduledRule:
    Type: AWS::Events::Rule
    Properties:
      ScheduleExpression: rate(1 day)
      State: ENABLED
      Targets:
        -
          Arn:
            Fn::GetAtt:
              - BigBrotherFunction
              - Arn
          Id: TargetFunctionV1
  PermissionForEventsToInvokeLambda:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName:
        Ref: BigBrotherFunction
      Action: lambda:InvokeFunction
      Principal: events.amazonaws.com
      SourceArn:
        Fn::GetAtt:
          - ScheduledRule
          - Arn
Outputs:
  BigBrotherFunction:
    Value:
      Fn::GetAtt:
      - BigBrotherFunction
      - Arn
